openapi: 3.0.4
info:
  title: Спецификация для пользователей бонусной программы лояльности инвестиционного приложения
  version: 0.0.1
servers:
    - url: host
      description: Dev server
paths:
  /users:
    get:
      summary: Метод получения списка пользователей бонусной программы лояльности
      tags:
        - Users
      operationId: getAllusers
      responses:
        '200':
          description: Успешный ответ со списком пользователей бонусной программы
          content: 
             application/json: 
              schema:
                $ref: "#/components/schemas/UserValue"
        'default': 
          description: Все нестандартное
          content: 
            application/json:
              schema: 
                $ref: "#/components/schemas/Error"
    post:
      summary: Метод добавления нового пользователя бонусной программы лояльности
      tags:
        - Users
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreateRequest"
      responses:
        '201':
          description: Успешный ответ с одним пользователем
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserCreateResponse"
        'default':
          description: Все нестандартное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    UserValue:
      type: object
      required:
        - user_id
      properties:
        user_id:
          type: string
          example: 111
        surname:
          type: string
          example: Gulidova  
        name:
          type: string
          example: Veronika
        patronimic:
          type: string
          example: Vladimirovna
        isBlocked:
          type: boolean
          example: false

    UsersList:
      type: object
      required:
        - userValueList
      properties:
        userValueList:
          type: array
          items:
            $ref: "#/components/schemas/UserValue"

    UserCreateRequest:
      type: object
      required:
        - surname
        - name
        - patronimic
        - user_id
      properties:
        surname:
          type: string
          example: Gulidova
        name:
          type: string
          example: Veronika
        patronimic:
          type: string
          example: Vladimirovna
        user_id:
          type: string
          example: 111

    UserCreateResponse:
     allOf:
      - $ref: "#/components/schemas/UserValue"
      - type: object

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string